### ISSUE TITLE
User-adustable values for frequency band and threshold

### ISSUE THREAD

**Issue by staringispolite** [staringispolite/cochlea#3]
Let people adjust the frequency band and threshold for beat detection live.

Should be straightforward from a technical standpoint in Dendrite, unless there's some weird JS scope issues. Bigger question in my mind is how to add band selection, threshold selection, and GIPHY search, without the UI getting super cluttered

**Comment by staringispolite** [comment]
Should get a good cohesive design on this from @alexbaldwin too.

Possibly let users define a % of beats to respond to as well. Main concern is allowing all this flexibility while keeping the UI from getting cluttered, and keeping it simple/beginner-friendly "out of the box"

**Comment by alexbaldwin** [comment]
Coming in next PR.
